### ISSUE TITLE
Unexpected placeholder shadowing behavior

### ISSUE THREAD

**Issue by alextarrell** [pyrates/autoroutes#11]
Was adding some routes and noticed some URLs weren't matching how I expected. Namely when a pattern would shadow another:
```py
>>> from autoroutes import Routes
>>> routes = Routes()
>>> routes.add('root/{foo}')
>>> routes.add('root/foo/{bar}')
>>> routes.match('root/abc')
({}, {'foo': 'abc'})
>>> routes.match('root/foo/123')
(None, None)
```
I would expect the second match to be matched with the second route.

Some experimenting found another example:
```py
>>> from autoroutes import Routes
>>> routes = Routes()
>>> routes.add('root/{foo}')
>>> routes.add('root/{foo}/{bar}')
>>> routes.add('root/foo/{bar}')
>>> routes.match('root/abc')
({}, {'foo': 'abc'})
>>> routes.match('root/abc/123')
({}, {'foo': 'abc', 'bar': '123'})
>>> routes.match('root/foo/123')
({}, {'foo': 'foo', 'bar': '123'})
```
In this case the third match is being matched with the second route instead of the expected third route.

**Comment by yohanboniface** [comment]
Thanks for the report, I'll have a look!

**Comment by yohanboniface** [comment]
A few words on autoroute behaviour:

- order of route registering matters: autoroutes will honour the registering order while trying various candidates in some edge of the routes tree
- one way lookup: when autoroutes jump inside a branch of the routes tree, it will never goes up again

That said:
- you may control the order you register your routes
- we could try to make autoroutes always try static segments before variable ones (`/foo/` vs `/{foo}/`), but then users will lose control of the order, which may end with worse scenarios than the ones you describe
- we could try to teach autoroutes to go up in the tree when some branch is dead-end, but that's not an easy task

Now on your two scenarios:
- the second one does not seem to be a bug to me: the path does match the second route, and it respects the order the routes where registered
- the first one sound problematic to me anyway: the path `root/foo/123` does not strictly match the first route, because of the `/`, so I'd say that even with this registering order only the second route should match; so that one needs further investigation from my side

**Comment by yohanboniface** [comment]
Just pushed 0.3.5 version, can you have a look ?

**Comment by alextarrell** [comment]
Excellent! The first case is now working perfectly for me. I wasn't aware that route registration was order-dependent, but now that I do I can easily take that into account.

Thanks!

**Comment by yohanboniface** [comment]
>  I wasn't aware that route registration was order-dependent, but now that I do I can easily take that into account.

Just added a mention about that in the README. :)
